wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.4
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1720292045
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 19
      - 23
      4: 3.12.2
      5: 0.17.4
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
alpha:
  desc: null
  value: 0.1
gamma:
  desc: null
  value: 0.99
epsilon_start:
  desc: null
  value: 1.0
epsilon_min:
  desc: null
  value: 0.1
epsilon_decay:
  desc: null
  value: 0.995
num_episodes:
  desc: null
  value: 1000
state_size:
  desc: null
  value:
  - 50
  - 50
  - 50
action_size:
  desc: null
  value: 3
