program: main.py
method: bayes
metric:
  name: Average Reward
  goal: maximize
parameters:
  K:
    values: [1000, 2000, 5000]
  N:
    values: [50, 100, 500]
  L:
    values: [10, 20, 50]
  alpha_start:
    min: 0.01
    max: 0.9
  alpha_end:
    min: 0.001
    max: 0.1
  alpha_decay:
    min: 0.9
    max: 1.0
  gamma:
    min: 0.9
    max: 0.99
  epsilon_start:
    min: 0.5
    max: 1.0
  epsilon_end:
    min: 0.01
    max: 0.1
  epsilon_decay:
    min: 0.9
    max: 1.0
project: taxi-v3-q-learning
